using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Compiler.Mods
{
    public enum Attribute
    {
        None = -1,
        HitPoints = 0,
        LineOfSight = 1,
        GarrisonCapacity = 2,
        SizeX = 3,
        SizeY = 4,
        MovementSpeed = 5,
        RotationSpeed = 6,
        Armor = 8,
        Attack = 9,
        ReloadTime = 10,
        AccuracyPercent = 11,
        MaxRange = 12,
        WorkRate = 13,
        CarryCapacity = 14,
        BaseArmor = 15,
        ProjectileUnit = 16,
        IconAngle = 17,
        TerrainDefenceBonus = 18,
        EnableSmartProjectiles = 19, // ballistics?
        MinRange = 20,
        ResourceStorage = 21,
        BlastWidth = 22,
        SearchRadius = 23,
        ResourceCost = 100,
        TrainTime = 101,
        TotalMissiles = 102,
        FoodCost = 103,
        WoodCost = 104,
        GoldCost = 105,
        StoneCost = 106,
        MaxTotalMissiles = 107,
        GarrisonHealRate = 108
    }

    public enum Resource
    {
        Food,
        Wood,
        Stone,
        Gold,
        PopulationCap,
        Religion,
        CurrentAge,
        Relics,
        TradeBonus,
        TradeGoods,
        TradeProduction,
        Population,
        Decay,
        Discovery,
        Ruins,
        Meat,
        Berries,
        Fish,
        Kills = 20,
        ResearchCount,
        Exploration,
        ConvertMonk = 27,
        ConvertBuilding,
        BuildingLimit = 30,
        FoodLimit,
        UnitLimit,
        Maintenance,
        Faith,
        FaithRechargeRate,
        FarmFood,
        CivilianPopulation,
        AllTechsAchieved = 39,
        MilitaryPopulation,
        Conversions,
        Wonder,
        Razings,
        KillRatio,
        PlayerKilled,
        TributeInefficiency,
        GoldBonus,
        TownCenterUnavailable,
        GoldCounter,
        Writing,
        Monasteries = 52,
        Tribute,
        HoldRuins,
        HoldRelics,
        Ore,
        CapturedUnit,
        TradeGoodQuality = 59,
        TradeMarketLevel,
        Formations,
        BuildingHousingRate,
        GatherTaxRate,
        GatherAccumulator,
        SalvageDecayRate,
        AllowFormations,
        CanConvert,
        Player1Kills = 69,
        Player2Kills,
        Player3Kills,
        Player4Kills,
        Player5Kills,
        Player6Kills,
        Player7Kills,
        Player8Kills,
        ConvertResistance,
        TradeVigRate,
        StoneBonus,
        QueuedCount,
        TrainingCount,
        Raider,
        BoardingRechargeRate,
        StartingVillagers,
        ResearchCostMod,
        ResearchTimeMod,
        ConvertBoats,
        FishTrapFood,
        HealRateModifier,
        HealRange,
        StartingFood,
        StartingWood,
        StartingStone,
        StartingGold,
        RaiderAbility,
        BerserkerHealTimer,
        DominantSheepControl,
        ObjectCostSummation,
        ResearchSummation,
        RelicIncomeSummation,
        TradeIncomeSummation,
        Player1Tribute,
        Player2Tribute,
        Player3Tribute,
        Player4Tribute,
        Player5Tribute,
        Player6Tribute,
        Player7Tribute,
        Player8Tribute,
        Player1KillValue,
        Player2KillValue,
        Player3KillValue,
        Player4KillValue,
        Player6KillValue,
        Player7KillValue,
        Player8KillValue,
        Player1Razings,
        Player2Razings,
        Player3Razings,
        Player4Razings,
        Player5Razings,
        Player6Razings,
        Player7Razings,
        Player8Razings,
        Player1RazingValue,
        Player2RazingValue,
        Player3RazingValue,
        Player4RazingValue,
        Player5RazingValue,
        Player6RazingValue,
        Player7RazingValue,
        Player8RazingValue,
        Castle,
        KillsByPlayer1 = 136,
        KillsByPlayer2,
        KillsByPlayer3,
        KillsByPlayer4,
        KillsByPlayer5,
        KillsByPlayer6,
        KillsByPlayer7,
        KillsByPlayer8,
        RazingsByPlayer1,
        RazingsByPlayer2,
        RazingsByPlayer3,
        RazingsByPlayer4,
        RazingsByPlayer5,
        RazingsByPlayer6,
        RazingsByPlayer7,
        RazingsByPlayer8,
        ValueKilledByOthers,
        ValueRazedByOthers,
        KilledByOthers,
        RazedByOthers,
        TributeFromPlayer1,
        TributeFromPlayer2,
        TributeFromPlayer3,
        TributeFromPlayer4,
        TributeFromPlayer5,
        TributeFromPlayer6,
        TributeFromPlayer7,
        TributeFromPlayer8,
        ValueCurrentUnits,
        ValueCurrentBuildings,
        FoodTotal,
        WoodTotal,
        StoneTotal,
        GoldTotal,
        TotalValueOfKills,
        TotalTributeReceived,
        TotalValueOfRazings,
        TotalCastlesBuilt,
        TotalWondersBuilt,
        TributeScore,
        ConvertMinAdj,
        ConvertMaxAdj,
        ConvertResistMinAdj,
        ConvertResistMaxAdj,
        ConvertBuildingMin,
        ConvertBuildingMax,
        ConvertBuildingChance,
        Spies,
        ValueWondersCastles,
        FoodScore,
        WoodScore,
        StoneScore,
        GoldScore,
        WoodBonus,
        FoodBonus,
        RelicRate,
        Heresy,
        Theocracy,
        Crenellations,
        ConstructionRateMod,
        HunWonderBonus,
        SpiesDiscount
    }
}
